package ludumdare38;


class GameTexts 
{

	public static var GAME_TITLE:String = "SMALL TACTICS";
	public static var GAME_START:String = "SURVIVAL (1 PLAYER)";
	public static var GAME_VERSUS:String = "VERSUS (2 PLAYER)";
	public static var GAME_HELP:String = "HOW TO PLAY";
	public static var GAME_MENU:String = "GO TO MENU";
	public static var GAME_CREDITS:String = "Game made by @JanGamesDev";
	
	public static var GAME_END_SURVIVAL_PREFIX:String = "YOUR SURVIVED\n";
	public static var GAME_END_SURVIVAL_POSTFIX:String = "\nDAYS";
	public static var GAME_END_PLAYER1_WON:String = "PLAYER 1 WON!";
	public static var GAME_END_PLAYER2_WON:String = "PLAYER 2 WON!";
	
	public static var GAME_UI_SKIP:String = "END\nTURN";
	public static var GAME_UI_WOOD:String = "WOOD";
	public static var GAME_UI_IRON:String = "IRON";
	public static var GAME_UI_PEOPLE:String = "PEOPLE";
	
	public static var HELP_BASICS_TITLE:String = "BASICS";
	public static var HELP_BASIC_UNITS:String = "UNITS CAN MOVE ONCE PER TURN BY CLICKING THEM AND THEN CLICKING\nON THE GREEN ZONE.\nIF THE SAME CELL IS CHOSEN THE UNIT WILL GO INTO ACTION MODE.\nANY UNIT CAN PERFORM AN ACTION (ATTACK OR BUILD) PER TURN.\n";
	public static var HELP_BASIC_BUILDINGS:String = "BUILDINGS HELP THE PLAYER CREATE UNITS OR GENERATE RESOURCES.\nOVERING A BUILDING WILL SHOW YOU THE CREATION BAR.\nCLICKING ON THE BUILDING LETS YOU CHOOSE THE UNIT YOU WANT TO CREATE.\nRESOURCE GENERATION BUILDING GIVE RESOURCES AT THE START OF THE TURN.";
	public static var HELP_BASIC_RESOURCES:String = "YOU HAVE 3 DIFFERENT RESOURCES WOOD, IRON AND PEOPLE.\nEACH UNIT/BUILDING REQUIRES A SPECIFIC AMMOUNT OF EACH RESOURCE";
	public static var HELP_BASIC_TURNEND:String = "YOUR TURN END WHEN ";
	public static var HELP_UNITS_TITLE:String = "UNITS";
	public static var HELP_UNITS_BUILDER:String = "BUILDER: BASIC CONSTRUCTION UNIT, CANNOT ATTACK, LOW LIFE, GOOD MOBILITY";
	public static var HELP_UNITS_LANCER:String = "LANCER: MELEE RANGE UNIT, HIGH LIFE, GOOD MOBILITY";
	public static var HELP_UNITS_ARCHER:String = "ARCHER: LONG RANGE UNIT, LOW LIFE, NORMAL MOBILITY";
	public static var HELP_UNITS_ZOMBIE:String = "ZOMBIE: ENEMY UNIT (SURVIVAL ONLY), SLOW AND WEAK";
	public static var HELP_BUILDINGS_TITLE:String = "BUILDINGS";
	public static var HELP_BUILDINGS_CASTLE:String = "CASTLE: MAIN BUILDING, IF DESTROYED THE GAME IS OVER.\nCAN CREATE BUILDERS, LANCERS AND ARCHERS.\nGENERATES A SMALL AMMOUNT OF RESOURCES EACH TURN";
	public static var HELP_BUILDINGS_LUMBERMILL:String = "LUMBERMILL: GENERATES WOOD EACH TURN, CAN ONLY BE BUILT ON FORESTS.";
	public static var HELP_BUILDINGS_MINE:String = "MINE: GENERATES IRON EACH TURN, CAN ONLY BE BUILT ON CAVES.";
	public static var HELP_BUILDINGS_HOUSE:String = "HOUSE: GENERATES A SMALL AMMOUNT OF PEOPLE EACH TURN, CAN\nONLY BE BUILT ON GRASS.";
	public static var HELP_BUILDINGS_BARRACK:String = "BARRACK: CAN CREATE LANCERS AND ARCHERS, CAN ONLY BE BUILT ON GRASS.";
	public static var HELP_BUILDINGS_WALL:String = "WALL: DEFENSIVE BUILDING, HIGH AMMOUNT OF HP, CAN BE BUILT ANYWHERE.";
	
	public static var TURN_PLAYER:String = "PLAYER TURN";
	public static var TURN_ENEMY:String = "ENEMY TURN";
	
	public static var TURN_PLAYER_1:String = "PLAYER 1 TURN";
	public static var TURN_PLAYER_2:String = "PLAYER 2 TURN";
	
}